site_name: Technical Artist Roadmap
site_description: A comprehensive guide and resource collection for aspiring Technical Artists in the game industry
site_author: TA-Roadmap Contributors
repo_url: https://github.com/angelina007huang/TA-Roadmap
repo_name: TA-Roadmap
site_url: https://angelina007huang.github.io/TA-Roadmap/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            Home: 首页
            Getting Started: 入门指南
            Introduction: 简介
            Core Skills: 核心技能
            Specializations: 专业方向
            Pipeline: 管线开发
            Shaders & Graphics: 着色器和图形
            Animation: 动画技术
            VFX: 特效制作
            Tools: 工具开发
            Resources: 资源
            Learning Path: 学习路径
            Community: 社区
            Tools & Software: 工具和软件
            Contributing: 贡献指南

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/angelina007huang/TA-Roadmap
      name: GitHub Repository
    - icon: fontawesome/brands/discord
      link: https://discord.gg/tech-art
      name: Discord Community

nav:
  - Home: index.md
  - Getting Started:
    - ReadGuide: readguide.md
    - Core Skills: core-skills.md
  - Specializations:
    - Pipeline: specializations/pipeline.md
    - Shaders & Graphics: specializations/shaders-and-graphics.md
    - Animation: specializations/animation.md
    - VFX: specializations/vfx.md
    - Tools: specializations/tools.md
  - Resources:
    - Learning Path: resources/learning-path.md
    - Community: resources/community.md
    - Tools & Software: resources/tools-software.md
  - Contributing: contributing.md 