site_name: Technical Artist Roadmap
site_description: A comprehensive guide and resource collection for aspiring Technical Artists in the game industry
site_author: TA-Roadmap Contributors
repo_url: https://github.com/angelinahuang007/TA-Roadmap
repo_name: TA-Roadmap
site_url: https://angelinahuang007.github.io/TA-Roadmap/
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.sidebar
  - navigation.top
  - search.suggest
  - search.highlight
  language: zh
  palette:
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
extra_css:
- assets/css/custom.css
markdown_extensions:
- attr_list
- md_in_html
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.emoji:
    emoji_generator: svg
- admonition
- footnotes
- toc:
    permalink: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.details
plugins:
- i18n:
    languages:
    - locale: zh
      default: true
      name: 简体中文
      build: true
      nav_translations:
        index: 首页
        Home: 首页
        getting-started: 入门指南
        core-skills: 核心技能
        interview-prep: 面试准备
        specializations: 专业方向
        resources: 资源推荐
        art-fundamentals: 艺术基础
        computer-science: 计算机基础
        digital-design: 数字设计
        composition: 构图原理
        design-principles: 设计原则
        visual-elements: 视觉元素
        design-psychology: 设计心理学
        color-theory: 配色理论
        mathematics: 数学基础
        data-structures: 数据结构
        algorithms: 算法
        programming-languages: 编程语言
        computer-systems: 计算机系统
        software-engineering: 软件工程
        procedural-generation: 程序化生成
        shaders-and-graphics: 着色器和图形
        animation: 动画技术
        vfx: 特效制作
        tools: 工具开发
        pipeline: 管线开发
        learning-path: 学习路径
        community: 社区
        tools-software: 工具和软件
        bookrec: 好书推荐
        papers: 论文推荐
        uncategorized: 未分类资源
        start: 开始
        digitalDesign: 数字设计
        math: 数学
        dataStructure: 数据结构
        leetcodeCheatsheet: Leetcode速查表
        toolsnsoftware: 工具和软件
        paths: 学习路径
        contributing: 贡献指南
        fundamentals: 基础知识
        readguide: 阅读指南
        test: 测试页面
        python-packages: python包
    - locale: en
      name: English
      build: true
- search:
    lang:
    - zh
    - en
- redirects:
    redirect_maps:
      cheatsheet/index.md: 03_interview-prep/001_leetcodeCheatsheet.md
      en/cheatsheet/index.md: 03_interview-prep/001_leetcodeCheatsheet.en.md
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/angelina007huang/TA-Roadmap
    name: GitHub Repository
  - icon: fontawesome/brands/discord
    link: https://discord.gg/tech-art
    name: Discord Community
nav:
- Home: index.md
- getting-started:
  - start: 01_getting-started/001_start/verystart.md
- core-skills:
  - art-fundamentals:
    - digitalDesign: 02_core-skills/001_art-fundamentals/0001_digitalDesign.md
    - composition: 02_core-skills/001_art-fundamentals/0002_composition.md
  - computer-science:
    - math: 02_core-skills/002_computer-science/0001_math.md
    - dataStructure: 02_core-skills/002_computer-science/0002_dataStructure.md
- tools:
  - tools: 03_tools/001_tools.md
  - blender: 03_tools/002_blender.md
  - python-packages: 03_tools/003_python-packages.md
- interview-prep:
  - leetcodeCheatsheet: 04_interview-prep/001_leetcodeCheatsheet.md
- resources:
  - bookrec: 05_resources/001_bookrec.md
  - papers: 05_resources/002_papers.md
  - paths: 05_resources/003_paths.md
  - toolsnsoftware: 05_resources/004_toolsnsoftware.md
  - community: 05_resources/005_community.md
  - uncategorized: 05_resources/006_uncategorized.md
- specializations:
  - procedural-generation: 06_specializations/001_procedural-generation.md
