site_name: Technical Artist Roadmap
site_description: A comprehensive guide and resource collection for aspiring Technical Artists in the game industry
site_author: TA-Roadmap Contributors
repo_url: https://github.com/angelinahuang007/TA-Roadmap
repo_name: TA-Roadmap
site_url: https://angelinahuang007.github.io/TA-Roadmap/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.sidebar
    - search.suggest
    - search.highlight
  language: zh
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search:
      lang:
        - zh
        - en
  - i18n:
      docs_structure: folder
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            首页: Home
            入门指南: Getting Started
            前言: Preface
            核心技能: Core Skills
            专业方向: Specializations
            管线开发: Pipeline
            着色器和图形: Shaders & Graphics
            动画技术: Animation
            特效制作: VFX
            工具开发: Tools
            资源: Resources
            学习路径: Learning Path
            社区: Community
            工具和软件: Tools & Software
            贡献指南: Contributing
            

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/angelina007huang/TA-Roadmap
      name: GitHub Repository
    - icon: fontawesome/brands/discord
      link: https://discord.gg/tech-art
      name: Discord Community

nav:
  - 技术美术学习路线: 
    - 前言: index.md
    - 核心技能: core-skills.md
    - 管线开发: 
      - 技术1: pipeline/pipeline.md
      - 技术2: pipeline/pipeline.md
    - 着色器和图形: 
      - 技术1: shadersGraphics/shaders-and-graphics.md
      - 技术2: shadersGraphics/shaders-and-graphics.md
    - 动画技术: 
      - 技术1: animation/animation.md
      - 技术2: animation/animation.md
    - 特效制作: vfx/vfx.md
    - 工具开发: tools/tools.md
    - 资源:
      - 学习路径: resources/learning-path.md
      - 社区: resources/community.md
      - 工具和软件: resources/tools-software.md
    - 贡献指南: contributing.md
