name: Update MkDocs Navigation

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'docs/**'
      - '!.i18n/en.yml'  # Don't trigger on i18n changes to avoid loops
  pull_request:
    branches: [ main, master ]
    paths: 
      - 'docs/**'
      - '!.i18n/en.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-navigation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    
    - name: Make script executable
      run: chmod +x scripts/update_mkdocs.py
    
    - name: Update MkDocs navigation
      run: |
        python scripts/update_mkdocs.py
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Files changed:"
          git status --porcelain
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
    
    - name: Commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add mkdocs.yml .i18n/
        git commit -m "Auto-update mkdocs.yml navigation and i18n translations from docs structure" || exit 0
        echo "Changes committed locally. Please review and push manually when ready."
